### ISSUE TITLE
I got unexpected token in the package index file

### ISSUE THREAD

**Issue by lkousse** [paul-shuvo/nodejs-currency-converter#24]
/Users/lkousse/geektechnologiegroup/project-backend/node_modules/currency-converter-lt/index.js:7
    currencies = {
               ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/lkousse/geektechnologiegroup/project-backend/api/controllers/services.js:16:12)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at module.exports (/Users/lkousse/geektechnologiegroup/project-backend/api/routes/services.js:3:22)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by paul-shuvo** [comment]
which node version are you using?

**Comment by paul-shuvo** [comment]
I'm closing this issue for now.
